### ISSUE TITLE
Отсутствует url ссылки "скачать" на странице чтения документации, конкретной версии.

### ISSUE THREAD

**Issue by sergeytolkachyov** [SeptdirWorkshop/SWJProjects#101]
**Опишите ошибку**
Сабж. url для скачивания проекта не формируется.

**Как воспроизвести**
Шаги для воспроизведения ошибки:
1. Создайте тестовый проект, версию, документацию (как категорию) и страницу документации.
2. Перейдите на страницу чтения документации или на страницу просмотра конкретной версии
3. Попытайтесь скачать проект.
4. Смотрите ошибку в url тега <a> - Warning: Undefined property: stdClass::$download in /components/com_swjprojects/views/version/tmpl/default_j4.php on line 85
5. 

**Ожидаемое поведение**
Файл скачивается

**Информация о системе (пожалуйста, заполните следующую информацию):**
  - Версия Расширения [например, 1.6.1]

**Comment by joomlaphp** [comment]
Yes, I tried this latest version 1.6.2, it doesn't download, it throws it on the jooma homepage.
