### ISSUE TITLE
[Global] Fix languages

### ISSUE THREAD

**Issue by Septdir** [SeptdirWorkshop/SWJProjects#50]
Испрвить ошибки и опечатки в русском языке.

* Список изменений | Список изменений
* Отблагодартить | Поддержать

**Comment by b2z** [comment]
COM_SWJPROJECTS_VERSION_CHANGELOG = "Список изминений"
COM_SWJPROJECTS_VERSION_CHANGELOG = "Список изменений"

COM_SWJPROJECTS_CATEGORY_PARENT = "Родительский категория"
COM_SWJPROJECTS_CATEGORY_PARENT = "Родительская категория"

COM_SWJPROJECTS_ELEMENT_DESCRIPTION = "Элемент используеться в качестве файлов"
COM_SWJPROJECTS_ELEMENT_DESCRIPTION = "Элемент используется в качестве файлов"

COM_SWJPROJECTS_DATE_END = "Дата оканчания"
COM_SWJPROJECTS_DATE_END_ASC = "Дата оканчания (по возрастанию)"
COM_SWJPROJECTS_DATE_END_DESC = "Дата оканчания (по убыванию)"
оканчания -> окончания

COM_SWJPROJECTS_PARAMS_FILES_FOLDER_DESC = "Если изменяете этот параметр не забудьте принести папку"
COM_SWJPROJECTS_PARAMS_IMAGES_FOLDER_DESC = "Если изменяете этот параметр не забудьте принести папку"
принести -> перенести

COM_SWJPROJECTS_PARAMS_KEY_LENGTH = "Длинна"
COM_SWJPROJECTS_PARAMS_KEY_LENGTH = "Длина"

COM_SWJPROJECTS_KEY_REGENERATE = "Re-generate"
COM_SWJPROJECTS_KEY_REGENERATE = "Regenerate"

COM_SWJPROJECTS_ELEMENT_DESCRIPTION = "Element use for filenames"
COM_SWJPROJECTS_ELEMENT_DESCRIPTION = "Element is used for filenames"

COM_SWJPROJECTS_FILE_NOT_EXIST = "File not fount"
COM_SWJPROJECTS_FILE_NOT_EXIST = "File not found"

COM_SWJPROJECTS_IMAGES_AVAILABLE = "Images available after saving"
COM_SWJPROJECTS_IMAGES_AVAILABLE = "Images are available after saving"

COM_SWJPROJECTS_PARAMS_FILES_FOLDER_DESC = "If you change this parameter, be sure to bring a folder"
COM_SWJPROJECTS_PARAMS_IMAGES_FOLDER_DESC = "If you change this parameter, be sure to bring a folder"
bring -> move
