### ISSUE TITLE
Documentation - exception

### ISSUE THREAD

**Issue by pv501977** [SeptdirWorkshop/SWJProjects#65]
Documentation page generate exception - The item documentation not exist in the $project.
 - file com_swjprojects/site/views/documentation/view.html.php
 - line 293
 (same problem could be on more places)

How simulate it:
 - index.php?option=com_swjprojects&view=documentation&id=1&catid=1&Itemid=233
 - index.php?option=com_swjprojects&view=documentation&id=1:....
    - show Documentation Window

Administration: Documentation exists - see picture.
![exception](https://user-images.githubusercontent.com/25018206/73305047-acdcf980-4219-11ea-880d-33465eb3ad02.png)
![jce](https://user-images.githubusercontent.com/25018206/73305048-acdcf980-4219-11ea-89ae-051c40e4cf09.png)

**Comment by Septdir** [comment]
Thank you Correct in the next version
