### ISSUE TITLE
SWJProjects 1.5.3 Bug

### ISSUE THREAD

**Issue by joomlaphp** [SeptdirWorkshop/SWJProjects#70]
Hi,
I am creating a new project. The moment I select a project from the version page, it gives an error.

Steps:
1. Go to 'swjprojects'
2. Click on 'Versions and New button'
3. I select the project from the drop down menu.
4. **An error has occurred. (0 Call to a member function filter() on null)**

Screenshots:
1. http://kilitlitorba.com/images/1.jpg
2. http://kilitlitorba.com/images/2.jpg

System Information:
- Joomla version: 3.9.16 stable
 - Extensions version [1.5.3]
 - PHP version: [7.2.28]
 - Server OS: [Linux]
 - Browser [chrome]

Best Regards
Ugur

**Comment by Septdir** [comment]
@joomlaphp Thank you for your observation.
I released a new version, you can update

**Comment by joomlaphp** [comment]
Thank you so much
