### ISSUE TITLE
Incorrect datetime value: '' for column 'date_end' at row 1

### ISSUE THREAD

**Issue by sergeytolkachyov** [SeptdirWorkshop/SWJProjects#87]
**Describe the bug**
Возникает ошибка **Incorrect datetime value: '' for column 'date_end' at row 1** при сохранении ключа

**To Reproduce**
1. Создаем ключ
2. Нажимаем "сохранить"
3. Для даты начала действия ключа прописывается текущая дата и время автоматом, для даты окончания действия ключа - пусто. Мы остаемся во index.php?option=com_swjprojects&view=key&layout=edit
4. Нажимаем "сохранить и закрыть" - возникает ошибка **Incorrect datetime value: '' for column 'date_end' at row 1**. Редактирование не закрывается. 
5. Если просто "сохранить" - ошибки нет. Если просто "закрыть" - ошибки нет.

Чистая джумла 4.1.2, чистая установка SW JProjects 1.6-dev, только что скачанная с гитхаба.
![image](https://user-images.githubusercontent.com/6236403/165886456-b4f247fe-960d-4e12-9278-6a0b27a95004.png)

**Comment by Septdir** [comment]
done
