### ISSUE TITLE
Нельзя просто закрыть создание версии без заполненных полей версии

### ISSUE THREAD

**Issue by sergeytolkachyov** [SeptdirWorkshop/SWJProjects#88]
**Describe the bug**
Нельзя просто закрыть создание версии без заполненных полей версии.

**To Reproduce**
1. Версии - "Создать"
2. НИЧЕГО не заполняем и сразу нажимаем "закрыть"
3. Видим ошибку

https://user-images.githubusercontent.com/6236403/165886858-d974f276-1725-4113-a44b-a4f0b404d65b.mp4

**Comment by Septdir** [comment]
done
