### ISSUE TITLE
Поле выбора версии Joomla при создании версии появляется только после сохранения

### ISSUE THREAD

**Issue by sergeytolkachyov** [SeptdirWorkshop/SWJProjects#89]
**Describe the bug**
Поле выбора версии Joomla при создании версии появляется только после сохранения

**To Reproduce**
1. Версии - "Создать"
2. Увидеть, что поля "Версия Joomla" нет.
3. Сохранить версию
4. Увидеть, что поле "версия Joomla" появилось.

https://user-images.githubusercontent.com/6236403/165887439-66dd9f28-be92-4d0f-835a-ff3422d40653.mp4

**Comment by Septdir** [comment]
Done
