### ISSUE TITLE
Колонка сортировки по Агенту в админке

### ISSUE THREAD

**Issue by Sulpher** [SeptdirWorkshop/SWJProjects#94]
сабж. отсортировать все проекты/файлы и т.п. конкретного агента7

**Comment by Sulpher** [comment]
вот агент: (условно говоря, к какому пользователю прикреплен проект)
<img width="1074" alt="Снимок экрана 2023-04-13 в 15 39 20" src="https://user-images.githubusercontent.com/3432048/231761070-5c3ceecc-f0b2-49c4-9558-7ff0de9446dd.png">

а вот в списке проектов  хорошо бы сделать параметр в фильтре для сортировки по агенту (список с выбором агента как материалы юзера)

**Comment by sergeytolkachyov** [comment]
@Sulpher если это в sovmart, то там своя песня. По сути это отдельный форк, который сам развивается. В обычном sw jprojects такого нет

**Comment by Sulpher** [comment]
да, это sovmart. понял.
